using KibiHex.MathsGen.CodeModel;

namespace KibiHex.MathsGen.Model.Rendering
{
    internal sealed class CSharpRenderer
    {
        private readonly TypeRenderer types = new();

        public string Render(TypeSpec type, TypePart part = TypePart.Core)
        {
            var writer = new CodeWriter();
            writer.Line("// <auto-generated />");
            writer.Line("#nullable enable");
            writer.Line("using System;");
            writer.Line("using System.Runtime.InteropServices;");
            writer.Line("using System.Runtime.CompilerServices;");
            writer.Line();
            writer.Block($"namespace {type.Namespace}", () => types.Render(writer, type, part));
            return writer.ToString();
        }
    }
}
