using Delta.MathsGen.CodeModel;

namespace Delta.MathsGen.Model.Rendering
{
    internal sealed class CSharpRenderer
    {
        private readonly string _autoGeneratedMarker;

        public CSharpRenderer()
        {
            _autoGeneratedMarker = "// <auto-generated />";
        }

        public string Render(TypeSpec type, TypePart part = TypePart.Core)
        {
            var writer = new CodeWriter();
            writer.Line(_autoGeneratedMarker);
            writer.Line("#nullable enable");
            writer.Line("using System;");
            writer.Line("using System.Runtime.InteropServices;");
            writer.Line("using System.Runtime.CompilerServices;");
            writer.Line();
            writer.Block($"namespace {type.Namespace}", () => TypeRenderer.Render(writer, type, part));
            return writer.ToString();
        }
    }
}
