using System;
using System.Collections.Generic;
using System.Linq;
using DeltaMathsGen.CodeModel;

namespace DeltaMathsGen.Model.Rendering
{
    internal static class ShaderDeltaMathsRenderer
    {
        public static bool CanRender(IReadOnlyList<TypeSpec> types) => ShaderDeltaMathsFunctions(types).Length != 0;

        public static string Render(IReadOnlyList<TypeSpec> types)
        {
            var functions = ShaderDeltaMathsFunctions(types).ToArray();
            if (functions.Length == 0)
            {
                throw new InvalidOperationException("No shader maths functions found.");
            }

            var writer = new CodeWriter();
            writer.Line("// <auto-generated />");
            writer.Line("#pragma warning disable IDE1006");
            writer.Line("#nullable enable");
            writer.Line("using System.Runtime.CompilerServices;");
            writer.Line();
            writer.Block("namespace DeltaMaths", () =>
            {
                writer.Block("public static partial class maths", () =>
                {
                    foreach (var item in functions)
                    {
                        writer.Line();
                        RenderFunction(writer, item.Type, item.Function);
                    }
                });
            });
            return writer.ToString();
        }

        private static void RenderFunction(CodeWriter writer, TypeSpec type, FunctionSpec function)
        {
            var signature = $"public static {function.ReturnType} {function.DeltaMathsName}({SyntaxFormatter.Parameters(function.Parameters)})";
            writer.Line("[MethodImpl(MethodImplOptions.AggressiveInlining)]");

            if (function.Targets.HasFlag(FunctionTargets.Type))
            {
                var arguments = string.Join(", ", function.Parameters.Select(parameter =>
                    parameter.Modifier == ParameterModifier.None
                        ? parameter.Name
                        : ShaderMetadata.ModifierToken(parameter.Modifier) + " " + parameter.Name));
                writer.Line($"{signature} => {type.Name}.{function.Name}({arguments});");
            }
            else if (!string.IsNullOrWhiteSpace(function.Expression))
            {
                writer.Line($"{signature} => {function.Expression};");
            }
            else
            {
                BodyRenderer.Block(writer, signature, function.Body);
            }
        }

        private static (TypeSpec Type, FunctionSpec Function)[] ShaderDeltaMathsFunctions(IReadOnlyList<TypeSpec> types) =>
            types.SelectMany(type => type.Members
                .OfType<FunctionSpec>()
                .Where(function => function.Targets.HasFlag(FunctionTargets.ShaderDeltaMaths))
                .Select(function => (type, function))).ToArray();
    }
}
