using System;
using Delta.MathsGen.CodeModel;

namespace Delta.MathsGen.Model.Rendering
{
    /// <summary>Renders the lowercase scalar maths façade.</summary>
    public sealed class ScalarDeltaMathsRenderer
    {
        private readonly string _namespace;

        /// <summary>Initializes a renderer for the Delta.Maths namespace.</summary>
        public ScalarDeltaMathsRenderer()
        {
            _namespace = "Delta.Maths";
        }

        /// <summary>Renders forwarding methods for the supplied scalar declarations.</summary>
        public string Render(ScalarMathMethod[] methods)
        {
            var writer = new CodeWriter();
            writer.Line("// <auto-generated />");
            writer.Line("#pragma warning disable IDE1006");
            writer.Line("#nullable enable");
            writer.Line();
            writer.Block($"namespace {_namespace}", () =>
            {
                writer.Block("public static partial class maths", () =>
                {
                    foreach (var method in methods)
                    {
                        if (method.Parameters.Contains('<', StringComparison.Ordinal))
                        {
                            continue;
                        }

                        writer.Line($"public static {method.ReturnType} {Lowercase(method.Name)}({method.Parameters}) => DeltaMaths.{method.Name}({method.Arguments});");
                    }
                });
            });
            return writer.ToString();
        }

        private static string Lowercase(string name) => string.IsNullOrEmpty(name) ? name : char.ToLowerInvariant(name[0]) + name[1..];
    }
}
